# Generated by Django 5.0.2 on 2024-02-17 15:32

import django.db.models.deletion
import ridivapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.FloatField(validators=[ridivapi.models.non_negative_validator])),
                ('price', models.FloatField(validators=[ridivapi.models.non_negative_validator])),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ridivapi.invoice')),
            ],
            options={
                'unique_together': {('invoice',)},
            },
        ),
    ]
