# Generated by Django 5.0.2 on 2024-02-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridivapi', '0002_alter_invoicedetail_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='description',
            field=models.TextField(unique=True),
        ),
    ]
