# Generated by Django 5.0.2 on 2024-02-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridivapi', '0003_alter_invoicedetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='description',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
