# Generated by Django 5.0.2 on 2024-02-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridivapi', '0004_alter_invoicedetail_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('date', 'customer')},
        ),
    ]
