# Generated by Django 5.0.2 on 2024-02-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridivapi', '0006_alter_invoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='invoicedetail',
            unique_together={('description', 'invoice')},
        ),
    ]
